{
  "holding": ["holding", "carry", "grasp", "grabbing", "cầm", "đang cầm"],
  "on": ["on", "on top of", "on", "trên", "đặt trên"],
  "next to": ["next to", "beside", "beside", "kế bên", "bên cạnh"],
  "in front of": ["in front of", "in front", "phía trước", "đằng trước"],
  "behind": ["behind", "phía sau", "đằng sau"],
  "under": ["under", "beneath", "dưới"],
  "left of": ["left of", "on the left of", "bên trái", "trái"],
  "right of": ["right of", "on the right of", "bên phải", "phải"],
  "between": ["between", "ở giữa", "giữa"],
  "inside": ["inside", "within", "in", "bên trong", "trong"],
  "outside": ["outside", "out of", "bên ngoài", "ngoài"],
  "above": ["above", "over", "phía trên", "ở trên"],
  "below": ["below", "underneath", "phía dưới", "bên dưới"],
  "near": ["near", "close to", "gần"],
  "far from": ["far from", "xa", "cách xa"],
  "around": ["around", "surrounding", "xung quanh"],
  "at": ["at", "tại"],
  "across from": ["across from", "opposite", "đối diện", "bên kia"],
  "along": ["along", "dọc theo"],
  "through": ["through", "xuyên qua"],
  "into": ["into", "vào trong"],
  "out of": ["out of", "ra khỏi"],
  "toward": ["toward", "to", "về phía"],
  "away from": ["away from", "rời khỏi"],
  "onto": ["onto", "lên trên"],
  "off": ["off", "ra khỏi", "tuột khỏi"],
  "past": ["past", "vượt qua", "đi qua"],
  "against": ["against", "chống lại", "tựa vào"],
  "among": ["among", "giữa (trong số nhiều)"],
  "beyond": ["beyond", "bên kia", "vượt qua"],
  "by": ["by", "bên cạnh", "qua"],
  "before": ["before", "trước (về thời gian/không gian)"],
  "attached to": ["attached to", "được gắn vào", "gắn với"],
  "nearby": ["nearby", "gần đây", "gần bên"],
  "at the top of": ["at the top of", "ở đầu", "phần trên cùng"],
  "to the side of": ["to the side of", "bên hông của", "sát bên"],
  "alongside": ["alongside", "dọc theo bên cạnh"],
  "facing": ["facing", "facing toward", "đối diện", "hướng về"],
  "back to": ["back to", "with back facing", "quay lưng lại"],
  "tilted": ["tilted", "slanted", "nghiêng"],
  "upside down": ["upside down", "lộn ngược"],
  "sideways": ["sideways", "nghiêng sang bên"]
}
